apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`k3s.nginx`)
      kind: Rule
      services:
        - kind: Service
          name: nginx-service
          port: 80
